Gon branch
rmzaoo/dealit-frontend pull request #17
Opened 2022-06-22 11:31 UTC by GonVieira

Rasguem-me todo mê.

2022-06-22 12:09 UTC, rmzaoo requested changes
See the comments below

2022-06-22 12:09 UTC, rmzaoo commented on src/components/DashboardSideBarButton/style.ts
> +import { PrimaryButton } from "../PrimaryButton/style";
wrong import

2022-06-22 12:09 UTC, rmzaoo commented on src/components/DashboardSideBarButton/style.ts
> +import { SecundaryButtonStyle } from "../SecundaryButton/style";
wrong import

2022-06-22 12:09 UTC, rmzaoo commented on src/components/ProductDetailsBuyInfo/ProductDetailsBuyInfo.tsx
> +            <StyledQuantityDropown
change to input, so If I want 1000 batteries for example I can't buy

2022-06-22 12:09 UTC, rmzaoo commented on src/components/ProductDetailsBuyInfo/style.ts
>  import { ProductPriceContainer } from "../ProductDetailsInfo/style";
wrongimport

2022-06-22 12:09 UTC, rmzaoo commented on src/components/ProductDetailsBuyInfo/style.ts
> +import { SecundaryButtonStyle } from "../SecundaryButton/style";
wrong import

2022-06-22 12:09 UTC, rmzaoo commented on src/components/ProductDetailsBuyInfo/style.ts
>    @media screen and (max-width: 480px) {
why you have media queries and you dont use?

2022-06-22 12:09 UTC, rmzaoo commented on src/components/ProductDetailsBuyInfo/style.ts
>    @media screen and (max-width: 480px) {
same, media queries and there's nothing inside

2022-06-22 12:09 UTC, rmzaoo commented on src/components/ProductDetailsBuyInfo/style.ts
>    @media screen and (max-width: 480px) {
same, media queries and there's nothing inside

2022-06-22 12:09 UTC, rmzaoo commented on src/components/navbar/style.ts
> +  z-index: 1001;
why? 1001 z-index

2022-06-22 12:09 UTC, rmzaoo commented on src/pages/LogInSecurityPage/LogInSecurityPage.tsx
> +const LogInSecurityPage = () => {
i dont like this name, rename to something like account settings

2022-06-22 13:37 UTC, rmzaoo commented on src/components/CategoryBar/style.ts
> +  z-index: 1001;
@GonVieira Change z-index of caroussel with Style Components

2022-06-22 14:38 UTC, GonVieira commented on src/components/DashboardSideBarButton/DashboardSideBarButton.tsx
> +      {Object.entries(options).map((value: any[], key: any) => {
Because i need to use react-icons inside the Object and if i use Arrays with typescript it "barracatingzz".

2022-06-22 16:06 UTC, GonVieira commented on src/components/navbar/style.ts
> +  z-index: 1001;
Because react-carousel arrows have index value of 1000 and the only way do change that is by creating custom arrows.

2022-06-22 16:22 UTC, GonVieira commented on src/pages/PDP/PDP.tsx
> +      window.scroll(0,0);
To go to the top of the page since the component does not rerender.

2022-06-22 16:39 UTC, aparra-11 approved these changes

2022-06-23 08:53 UTC, rmzaoo requested changes
Check the comments below

2022-06-23 08:53 UTC, rmzaoo commented on src/pages/PDP/PDP.tsx
> +      window.scroll(0, 0);
🔨🔨

2022-06-23 11:46 UTC, rmzaoo requested changes

2022-06-23 11:46 UTC, rmzaoo commented on src/components/HeaderComponent/HeaderComponent.tsx
> +
rename component

2022-06-23 11:46 UTC, rmzaoo commented on src/components/OrderComponent/OrderComponent.tsx
> +const OrderComponent = () => {
rename component

2022-06-23 12:23 UTC, rmzaoo approved these changes

2022-06-23 12:23 UTC, merged